// One-off asset generator (npm run fonts:fetch), not part of the Vercel
// build. Downloads only the "latin" and "latin-ext" subsets Google already
// splits its fonts into (latin-ext carries č/ć/š/ž/đ) — self-hosting them
// removes the render-blocking request to fonts.googleapis.com and lets us
// preload the two files that gate the hero's first paint. Re-run this
// whenever the font stack in index.html's Google Fonts URL changes.
import { writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const fontsDir = path.join(root, "public/fonts");
const outCss = path.join(root, "src/fonts.css");

const GOOGLE_CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400;1,9..144,500&family=Manrope:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

function slugify(family) {
  return family.toLowerCase().replace(/\s+/g, "-");
}

async function main() {
  const res = await fetch(GOOGLE_CSS_URL, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`Google Fonts CSS fetch failed: ${res.status}`);
  const css = await res.text();

  // Each block is preceded by a `/* subset */` comment.
  const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]+)}/g;
  const faces = [];
  let match;
  while ((match = blockRe.exec(css))) {
    const [, subset, body] = match;
    if (!KEEP_SUBSETS.has(subset)) continue;

    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const style = /font-style:\s*(\w+)/.exec(body)?.[1] ?? "normal";
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1] ?? "400";
    const url = /src:\s*url\(([^)]+)\)/.exec(body)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(body)?.[1];
    if (!family || !url || !unicodeRange) continue;

    faces.push({ family, style, weight, subset, url, unicodeRange });
  }

  await mkdir(fontsDir, { recursive: true });

  let cssOut = "/* Generated by scripts/fetch-fonts.mjs — do not hand-edit. */\n";
  for (const face of faces) {
    const filename = `${slugify(face.family)}-${face.weight}-${face.style}-${face.subset}.woff2`;
    const filePath = path.join(fontsDir, filename);

    const fontRes = await fetch(face.url, { headers: { "User-Agent": UA } });
    if (!fontRes.ok) throw new Error(`Font file fetch failed (${face.url}): ${fontRes.status}`);
    const buf = Buffer.from(await fontRes.arrayBuffer());
    await writeFile(filePath, buf);

    cssOut += `
@font-face {
  font-family: '${face.family}';
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url('/fonts/${filename}') format('woff2');
  unicode-range: ${face.unicodeRange};
}
`;
    console.log(`  ${filename} (${(buf.length / 1024).toFixed(1)}KB)`);
  }

  await writeFile(outCss, cssOut);
  console.log(`\n${faces.length} font files written to public/fonts/, CSS written to src/fonts.css`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
